// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCABM95P-OS8QeH92RtkyxpWs-c0LrZADQ',
    appId: '1:992008318698:web:f64c3d8610192696077193',
    messagingSenderId: '992008318698',
    projectId: 'tremglobal-34927',
    authDomain: 'tremglobal-34927.firebaseapp.com',
    databaseURL: 'https://tremglobal-34927-default-rtdb.firebaseio.com',
    storageBucket: 'tremglobal-34927.appspot.com',
    measurementId: 'G-4265P7NM9W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1WnwIP1euBnc53GXPUBsczAdk223cj5E',
    appId: '1:992008318698:android:abd954299b33a350077193',
    messagingSenderId: '992008318698',
    projectId: 'tremglobal-34927',
    databaseURL: 'https://tremglobal-34927-default-rtdb.firebaseio.com',
    storageBucket: 'tremglobal-34927.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ__Pqk5xz7iRRcy0a2WUuJl-nppdSxlc',
    appId: '1:992008318698:ios:8b044cc55669cd51077193',
    messagingSenderId: '992008318698',
    projectId: 'tremglobal-34927',
    databaseURL: 'https://tremglobal-34927-default-rtdb.firebaseio.com',
    storageBucket: 'tremglobal-34927.appspot.com',
    iosClientId: '992008318698-osv6ed4kg8llov3n4gcklu3bfi39feko.apps.googleusercontent.com',
    iosBundleId: 'com.example.tremglobal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ__Pqk5xz7iRRcy0a2WUuJl-nppdSxlc',
    appId: '1:992008318698:ios:8b044cc55669cd51077193',
    messagingSenderId: '992008318698',
    projectId: 'tremglobal-34927',
    databaseURL: 'https://tremglobal-34927-default-rtdb.firebaseio.com',
    storageBucket: 'tremglobal-34927.appspot.com',
    iosClientId: '992008318698-osv6ed4kg8llov3n4gcklu3bfi39feko.apps.googleusercontent.com',
    iosBundleId: 'com.example.tremglobal',
  );
}
