class advisorInfoLists {
  static List<String> investmenAdvisors = [
    "AMİRERFAN YAGHOOBİAN",
    "BAHTIGÜL ÖZBAY",
    "BAKHTAWAR UMER",
    "BÜŞRA ÖZ",
    "CENNET YILDIZ",
    "DİLYARA SEİİTKAZİYEVA",
    "ELHAM BARAZANDEH",
    "HAMED TABAR",
    "IMADEDDİN YOUNİS",
    "LEYLA MARDANOVA",
    "MALEK ABOULHASSAN",
    "MEDİA ABTAHİ",
    "MİKHAİL SMURYGİN",
    "MOHAMED HESHAM",
    "MUHAMMAD BAİG",
    "PARİSA AZARİ HASHJİN",
    "POLAT NAİMOĞLU",
    "POUYA HABİBZADEH",
    "SARA ALİ",
    "SERDAR KERİMOV",
    "SEVİNCH MAMEDOVA",
    "SHEKERA AKMYRADOVA",
    "SHOKRULLAH AMİRİ",
    "SİNA GHOLİNEJAD",
    "ZEESHAN MOHAMMAD",
    "ZULEKHA JALİWALA",
  ];

  static List<String> depts = [
    "Farsça",
    "Rusça (Grand Sirkeci Ofis)",
    "Urduca",
    "İngilizce (Antalya Ofis)",
    "Rusça",
    "İngilizce",
    "Farsça",
    "Farsça",
    "Arapça",
    "Rusça (Antalya Ofis)",
    "Farsça",
    "Farsça",
    "Rusça",
    "Arapça",
    "Urduca",
    "Farsça",
    "Rusça (Antalya Ofis)",
    "Farsça",
    "Urduca",
    "Rusça",
    "Rusça",
    "Rusça",
    "İngilizce",
    "Farsça",
    "Urduca",
    "Urduca",
  ];

  static List<String> pics = [
    "assets/erfan.jpg",
    "assets/bahtgul.jpg",
    "assets/bakhtawar.jpg",
    "assets/playstore.png",
    "assets/cennet.jpg",
    "assets/dilyara.jpg",
    "assets/elham.jpg",
    "assets/playstore.png",
    "assets/imad.jpg",
    "assets/leyla.jpg",
    "assets/malek.jpg",
    "assets/media.jpg",
    "assets/mikhail.jpg",
    "assets/mohamed.jpg",
    "assets/playstore.png",
    "assets/parisa.jpg",
    "assets/polat.jpg",
    "assets/puoya.jpg",
    "assets/playstore.png",
    "assets/serdar.jpg",
    "assets/sevinch.jpg",
    "assets/playstore.png",
    "assets/playstore.png",
    "assets/sina.jpg",
    "assets/playstore.png",
    "assets/playstore.png",
  ];
}
